# Copyright (c) .NET Foundation and Contributors
# See LICENSE file in the project root for full license information.

parameters:
  - name: skipNuGetCache
    type: boolean
    default: false

steps:

- task: Cache@2
  displayName: Cache NuGet packages
  condition: >-
    and(
      succeeded(),
      not(${{ parameters.skipNuGetCache }}),
      eq(variables['StartReleaseCandidate'], false),
      not(startsWith(variables['Build.SourceBranch'], 'refs/tags/v'))
    )
  continueOnError: true
  inputs:
    key: 'nuget | **/packages.lock.json'
    path: $(UserProfile)/.nuget/packages
