# Copyright (c) .NET Foundation and Contributors
# See LICENSE file in the project root for full license information.

steps:

- task: PowerShell@2
  condition: >-
    and(
      succeeded(),
      eq(variables['StartReleaseCandidate'], false),
      not(startsWith(variables['Build.SourceBranch'], 'refs/tags/v'))
    )
  displayName: Get AssemblyNativeVersion version
  inputs:
    targetType: 'inline'
    script: |

      $assemblyInfoFiles = (Get-ChildItem -Path ".\*" -Include "AssemblyInfo.cs" -Recurse)

      $attributeRegex = [regex]::new('("AssemblyNativeVersion\(")|(\d+\.\d+\.\d+\.\d+)|(""\))')

      # read attribute from file
      $fileContent = Get-Content($assemblyInfoFiles[0])

      $attrib = $attributeRegex.Match($fileContent) 

      $nativeVersion = $attrib.Groups[2].value

      Write-Host "AssemblyNativeVersion is $nativeVersion"

      Write-Host "$("##vso[task.setvariable variable=NF_ASSEMBLY_NATIVE_VERSION]")$nativeVersion"
